---
- name: install
  package: name=nginx state=present
- name: enable slowcgi
  service: name=slowcgi enabled=yes
  notify:
    - restart slowcgi
- name: enable
  service: name=nginx enabled=yes
  notify:
    - restart nginx
- name: configure
  copy: src=roles/nginx/files/{{ item }} dest=/etc/nginx/{{ item }}
  with_items:
    - nginx.conf
  notify:
    - restart nginx

- name: install letsencrypt
  package: name=letskencrypt state=present
- name: prepare letsencrypt directory
  file: path=/etc/letsencrypt state=directory
# XXX: Generate OpenSSL private key:
# openssl genrsa -out /etc/ssl/letsencrypt/private/privkey.pem 2048
# XXX: only if key is not already there
#- name: generate letsencrypt key
#  command: letskencrypt -vn unobtanium.de git.unobtanium.de www.unobtanium.de
#- name: refresh letsencrypt certificate
#  command: letskencrypt -v unobtanium.de git.unobtanium.de www.unobtanium.de
