---
- name: install
  package: name=nginx state=present
- name: enable slowcgi
  service: name=slowcgi enabled=yes
  notify:
    - restart slowcgi
- name: enable
  service: name=nginx enabled=yes
  notify:
    - restart nginx
- name: configure
  copy: src=roles/nginx/files/{{ item }} dest=/etc/nginx/{{ item }}
  with_items:
    - fastcgi_params
    - nginx.conf
    - scgi_params
    - uwsgi_params
  notify:
    - restart nginx
