---
# - name: install
#   package: name=nginx state=latest
- name: enable
  command: rcctl enable nginx
- name: configure
  copy: src=roles/nginx/files/{{ item }} dest=/etc/nginx/{{ item }}
  with_items:
    - fastcgi_params
    - nginx.conf
    - scgi_params
    - uwsgi_params
  notify:
    - restart nginx
