# Missing
# - tor?
# - install py-netaddr on deploy host?
---
- hosts: unobtanium
  gather_facts: no
  tasks:
    - name: install python2
      raw: sh -c 'which python2.7 || pkg_add -z python-2'
      tags: python
      register: install_python
      changed_when: '"/usr/local/bin/python2.7" not in install_python.stdout'

- hosts: unobtanium
  vars_files:
    - vars/main.yml
  roles:
    - role: doas
      tags: auth
    - role: users
      tags: auth
    - role: packages
      tags: packages
    - role: services
      tags: services
    - role: tinc
      tags: tinc
    - role: network
      tags: network
    - role: nsd
      tags: dns
    - role: dn42
      tags: dn42
    - role: letsencrypt
      tags:
        - www
        - tls
    - role: nginx
      tags:
        - www
        - tls
    - role: smtpd
      tags: 
        - mail
        - tls
    - role: cvsync
      tags: cvsync
    - role: weechat
      tags: weechat
    - role: mosquitto
      tags:
        - mqtt
        - tls
    - role: gogs
      tags:
        - www
        - gogs
