# Missing
# - gogs
# - tor?
# - install py-netaddr on deploy host?
---
- hosts: charm
  tasks:
    - name: configure pkg
      copy: src=files/pkg.conf dest=/etc/pkg.conf
- hosts: charm
  vars_files:
    - vars/main.yml
  roles:
    - services
    - { role: tinc, tags: [ tinc ] }
    - { role: network, tags: [ network ] }
    - { role: nsd, tags: [ dns ] }
    - { role: dn42, tags: [ dn42 ] }
    - nginx
    - smtpd
    - cvsync
    - { role: packages, tags: [ packages ] }
    - weechat
    - mosquitto
