# Missing
# - cvsync
# - gogs
# - tor?
# - install py-netaddr on deploy host?
---
- hosts: charm
  tasks:
    - name: configure pkg
      copy: src=files/pkg.conf dest=/etc/pkg.conf
- hosts: charm
  roles:
    - { role: tinc, tags: ['tinc'] }
    - nginx
    - smtpd
    - network
    - weechat
    - { role: dn42, tags: ["dn42"] }
#     - name: install packages
#       package: name={{ item }} state=present
#       with_items:
#         - bash
#         - bzip2
#         - cvsync
#         - git
#         - iodine
#         - mtr
#         - ncdu
#         - lftp
#         - nmap
#         - pv
#         - pwgen
#         - tor
#         - vim
