# Missing
# - cvsync
# - gogs
# - tinc
# - tor?
---
- hosts: charm
  tasks:
    - name: configure pkg
      copy: src=files/pkg.conf dest=/etc/pkg.conf
- hosts: charm
  roles:
    - nginx
    - smtpd
    - network
    - weechat
    - dn42
#     - name: install packages
#       package: name={{ item }} state=present
#       with_items:
#         - bash
#         - bzip2
#         - cvsync
#         - git
#         - iodine
#         - mtr
#         - ncdu
#         - lftp
#         - nmap
#         - pv
#         - pwgen
#         - tinc
#         - tor
#         - vim
