---
- name: install packages
  openbsd_pkg: name={{ item }} state=present
  with_items:
    - bzip2
    - git
    - iodine
    - mtr--
    - ncdu
    - lftp
    - nmap
    - pv
    - pwgen
    - tor
    - neovim

- include: cleanup.yml
