---
- name: install packages
  package: name={{ item }} state=present
  with_items:
    - bzip2
    - git
    - iodine
    - mtr
    - ncdu
    - lftp
    - nmap
    - pv
    - pwgen
    - tor
    - vim
