---
- name: restart bgpd
  service: name=bgpd state=restarted
- name: reload bgp config
  command: bgpctl reload
- name: netstart
  command: sh /etc/netstart
- name: restart nsd
  service: name=nsd state=restarted
