---
- name: configure interfaces
  copy:
    src: "{{ role_path }}/files/hostname.{{ item }}"
    dest: "/etc/hostname.{{ item }}"
  with_items:
    - gif0
    - vio0

- name: configure PF
  copy:
    src: "{{ role_path }}/files/pf.conf"
    dest: /etc/pf.conf
  notify:
    - reload pf ruleset
