---
- name: configure interfaces
  template:
    src: "hostname.{{ item }}"
    dest: "/etc/hostname.{{ item }}"
  with_items:
    - gif0
    - vio0
  notify:
    - restart network

- name: configure PF
  template:
    src: pf.conf
    dest: /etc/pf.conf
  notify:
    - reload pf ruleset

- name: v6 ping fix
  cron:
    name: regular ping to fix hanging v6
    job: ping6 -c1 -n heise.de 2>/dev/null >/dev/null
