---
my:
  as: 4242422342
  router_id: 172.22.127.1
  networks:
    - 172.22.127.0/27
    - fd97:1c82:9447::/64
dns:
  zone: gbe.dn42.
  serial: 2
  v4:
    ns: "{{ my.router_id }}"
    charm: "{{ my.router_id }}"
    hydrogen: 172.22.127.2
  v6:
    ns: "fd97:1c82:9447::"
    charm: "fd97:1c82:9447::"
    hydrogen: "fd97:1c82:9447::1"
  cnames:
    lg: charm
peers:
  - name: moho
    as: 4242423754
    openvpn:
      remote: dn42.mholtz.de
      port: 30012
      tun: 3
    tunnels:
      - { r: 169.254.12.1, l: 169.254.12.2 }
  - name: nazco
    as: 76118
    tunnels:
      - { r: 172.23.138.1, l: 172.22.255.66 }
    openvpn:
      remote: dn42.peering.nazco.de
      port: 37165
      rport: 2626
      tun: 4
  - name: leeps
    as: 4242422344
    tunnels:
      - { r: 172.23.55.15, l: 172.22.255.91 }
    openvpn:
      port: 37176
      tun: 5
  - name: MWD
    as: 4242420002
    tunnels:
      - { r: 172.23.227.1, l: 172.22.255.72 }
      - { r: 'fd14:70d8:4a5a:1::1', l: 'fd14:70d8:4a5a:1::' }
    openvpn:
      remote: 103.24.132.66
      port: 37168
      rport: 57604
      tun: 6
  - name: space
    as: 4242422343
    tunnels:
      - { r: 172.22.255.73, l: 172.22.255.68 }
      - { r: 'fd14:70d8:4a5a::2', l: 'fd14:70d8:4a5a::' }
    openvpn:
      remote: the-space.agency
      port: 37171
      tun: 7
  - name: sammy
    as: 76175
    tunnels:
      - { r: 172.23.245.1, l: 172.22.255.84 }
      - { r: 'fd14:70d8:4a5a:3::6', l: 'fd14:70d8:4a5a:3::1' }
    openvpn:
      remote: border.dark-it.net
      port: 37172
      tun: 8
  - name: unbedenklich
    as: 4242420020
    tunnels:
      - { r: 172.22.255.86, l: 172.22.255.85 }
      - { r: 'fd14:70d8:4a5a:4::2', l: 'fd14:70d8:4a5a:4::1' }
    openvpn:
      remote: dn42peering.services.unbedenklich.net
      rport: 53020
      port: 37173
      tun: 9
  - name: qsx
    as: 4242427761
    tunnels:
      - { r: 169.254.42.5, l: 169.254.42.6 }
    openvpn:
      remote: blackhole.qsuscs.de
      port: 29971
      tun: 10
      do_compress: no
      extra: |
        cipher aes-256-cbc
  - name: pascal
    as: 4242420205
    tunnels:
      - { r: 172.20.234.1, l: 169.254.23.1 }
    openvpn:
      remote: dn42.root6.de
      port: 50005
      tun: 11
  - name: gruetzkopf
    as: 4242420442
    tunnels:
      - { r: 172.20.239.65, l: 169.254.0.1 }
      - { r: 'fd14:70d8:4a5a:11::2', l: 'fd14:70d8:4a5a:11::1' }
    openvpn:
      remote: daemon.gruetzkopf.org
      port: 4279
      tun: 12
  - name: gigadoc2
    as: 4242420003
    tunnels:
      - { r: 172.22.255.71, l: 169.254.0.2 }
      - { r: 'fd14:70d8:4a5a:8::2', l: 'fd14:70d8:4a5a:8::1' }
    openvpn:
      remote: dn42.nicht.jetzt
      port: 32754
      tun: 13
      extra: |
        cipher aes-256-cbc
  - name: subraum
    as: 4242422718
    tunnels:
      - { r: 169.254.1.2, l: 169.254.1.1 }
    openvpn:
      remote: hackerspace.c3pb.de
      port: 14778
      tun: 14
  - name: cccac
    as: 4242420241
    tunnels:
      - { r: 169.254.200.1, l: 169.254.201.1 }
      - { r: 'fd14:70d8:4a5a:200::1', l: 'fd14:70d8:4a5a:201::1' }
    openvpn:
      remote: 01.peer.aachen.ccc.de
      port: 6407
      rport: 53020
      tun: 15
      extra: |
        cipher aes-256-cbc
        float
  - name: nd
    as: 4242423558
    tunnels:
      - { r: 172.20.170.34, l: 172.20.170.33 }
      - { r: 'fd14:70d8:4a5a:2001::1', l: 'fd14:70d8:4a5a:2011::1' }
    openvpn:
      remote: 00.peer.notandy.de
      port: 14217
      tun: 16
      extra: |
        cipher aes-256-cbc
        float
  - name: pr0j3ctx
    as: 4242422424
    tunnels:
      - { r: 172.22.255.88, l: 172.22.255.87 }
      - { r: 'fd14:70d8:4a5a:5::2', l: 'fd14:70d8:4a5a:5::1' }
    openvpn:
      rport: 53020
      port: 37174
      remote: 2a02:c207:3000:9979:91:134:50:138
      tun: 17
      extra: |
        float
        proto udp6
  - name: stv0g
    as: 76100
    tunnels:
      - { l: 172.22.255.36, r: 172.22.255.37 }
      - { l: 'fd14:70d8:4a5a::', r: 'fd14:70d8:4a5a::1' }
    openvpn:
      remote: 2a03:b0c0:1:d0::2e3:c001
      extra: |
        float
      port: 31218
      rport: 37163
      tun: 18
  - name: unobtanium
    as: 4242422342
    tunnels:
      - { r: 172.22.127.2, l: 172.22.127.1 }
      - { r: "fd97:1c82:9447::1", l: "fd97:1c82:9447::" }
#   - name: nicoo
#     as: 4242422121
#     tunnels:
#       - { r: 172.22.247.15 }
#   - name: leroy
#     as: 76136
#     tunnels:
#       - { r: 172.23.253.1 }
#       - { r: 172.23.253.4 }
#       - { r: 'fd14:70d8:4a5a:6::2' }
#       - { r: 'fd14:70d8:4a5a:7::2' }
