---
my:
  as: 4242422342
  router_id: 172.22.127.1
peers:
  - name: sammy
    as: 76175
    tunnels:
      - { r: 172.23.245.1, l: 172.22.255.84 }
      - { r: 'fd14:70d8:4a5a:3::6', l: 'fd14:70d8:4a5a:3::1' }
    openvpn:
      remote: border.dark-it.net
      port: 37172
      tun: 12
  - name: nicoo
    as: 4242422121
    tunnels:
      - { r: 172.22.247.15 }
  - name: unbedenklich
    as: 4242420020
    tunnels:
      - { r: 172.22.255.86, l: 172.22.255.85 }
      - { r: 'fd14:70d8:4a5a:4::2', l: 'fd14:70d8:4a5a:4::1' }
    openvpn:
      remote: dn42peering.services.unbedenklich.net
      rport: 53020
      port: 37173
      tun: 13
  - name: pr0j3ctx
    as: 4242422424
    tunnels:
      - { r: 172.22.255.88, l: 172.22.255.87 }
      - { r: 'fd14:70d8:4a5a:5::2', l: 'fd14:70d8:4a5a:5::1' }
    openvpn:
      rport: 53020
      port: 37174
      remote: dn42.xt0.org
      tun: 14
  - name: leeps
    as: 4242422344
    tunnels:
      - { r: 172.23.55.15, l: 172.22.255.91 }
    openvpn:
      port: 37176
      tun: 6
  - name: leroy
    as: 76136
    tunnels:
      - { r: 172.23.253.1 }
      - { r: 172.23.253.4 }
      - { r: 'fd14:70d8:4a5a:6::2' }
      - { r: 'fd14:70d8:4a5a:7::2' }
  - name: feuerrot
    as: 76140
    tunnels: []
  - name: tioan
    as: 4242422323
    tunnels:
      - { r: 172.22.255.83 }
      - { r: 'fd14:70d8:4a5a:2::2' }
  - name: space
    as: 4242422343
    tunnels:
      - { r: 172.22.255.73, l: 172.22.255.68 }
      - { r: 'fd14:70d8:4a5a::2', l: 'fd14:70d8:4a5a::' }
    openvpn:
      remote: the-space.agency
      port: 37171
      tun: 10
  - name: MWD
    as: 4242420002
    tunnels:
      - { r: 172.23.227.1, l: 172.22.255.72 }
      - { r: 'fd14:70d8:4a5a:1::1', l: 'fd14:70d8:4a5a:1::' }
    openvpn:
      remote: 103.24.132.66
      port: 37168
      rport: 57604
      tun: 7
  - name: gigadoc2
    as: 4242420003
    tunnels:
      - { r: 172.22.255.71 }
      - { r: 'fd14:70d8:4a5a:8::2' }
      # - { r: 'fe80::200:5efe:52d:6031%gre1' }
  - name: nazco
    as: 76118
    tunnels:
      - { r: 172.23.138.1, l: 172.22.255.66 }
    openvpn:
      remote: dn42.peering.nazco.de
      port: 37165
      rport: 2626
      tun: 4
