---
my:
  as: 4242422342
  router_id: 172.22.127.1
peers:
  - name: sammy
    as: 76175
    tunnels:
      - { r: 172.23.245.1, l: 172.22.255.84 }
      - { r: 'fd14:70d8:4a5a:3::6', l: 'fd14:70d8:4a5a:3::1' }
    openvpn:
      remote: border.dark-it.net
      port: 37172
      tun: 12
  - name: nicoo
    as: 4242422121
    tunnels:
      - { r: 172.22.247.15 }
  - name: unbedenklich
    as: 4242420020
    tunnels:
      - { r: 172.22.255.86, l: 172.22.255.85 }
      - { r: 'fd14:70d8:4a5a:4::2', l: 'fd14:70d8:4a5a:4::1' }
    openvpn:
      remote: dn42peering.services.unbedenklich.net
      rport: 53020
      port: 37173
      tun: 13
  - name: pr0j3ctx
    as: 4242422424
    tunnels:
      - { r: 172.22.255.88, l: 172.22.255.87 }
      - { r: 'fd14:70d8:4a5a:5::2', l: 'fd14:70d8:4a5a:5::1' }
    openvpn:
      rport: 53020
      port: 37174
      remote: dn42.xt0.org
      tun: 14
  - name: crest
    as: 64828
    tunnels:
      - { r: 172.22.254.65 }
      - { r: 'fd2d:82f6:9b63:1::ac16:fe41' }
  - name: eri
    as: 4242421375
    tunnels:
      - { r: 172.23.64.1, l: 172.22.255.91 }
      - { r: 'fd14:70d8:4a5a:10::2', l: 'fd14:70d8:4a5a:10::1' }
    openvpn:
      remote: chelnok.de
      port: 2316
      tun: 16
  - name: florianb
    as: 4242423955
    tunnels:
      - { r: 172.20.2.17, l: 172.22.255.93 }
    openvpn:
      remote: 5.1.86.30
      port: 37177
      tun: 17
  - name: leeps
    as: 4242422344
    tunnels:
      - { r: 172.23.55.15, l: 172.22.255.91 }
    openvpn:
      port: 37176
      tun: 6
  - name: leroy
    as: 76136
    tunnels:
      - { r: 172.23.253.1 }
      - { r: 172.23.253.4 }
      - { r: 'fd14:70d8:4a5a:6::2' }
      - { r: 'fd14:70d8:4a5a:7::2' }
  - name: feuerrot
    as: 76140
    tunnels: []
  - name: tioan
    as: 4242422323
    tunnels:
      - { r: 172.22.255.83 }
      - { r: 'fd14:70d8:4a5a:2::2' }
  - name: space
    as: 4242422343
    tunnels:
      - { r: 172.22.255.73, l: 172.22.255.68 }
      - { r: 'fd14:70d8:4a5a::2', l: 'fd14:70d8:4a5a::' }
    openvpn:
      remote: the-space.agency
      port: 37171
      tun: 10
  - name: packbart
    as: 4242420042
    tunnels:
      - { r: 172.23.232.81, l: 172.22.255.74 }
    openvpn:
      remote: vpn-farhaven.dn42.openchaos.org
      rport: 1809
      port: 37170
      tun: 9
  - name: mwheeler
    as: 4242420004
    tunnels:
      - { r: 172.23.221.3, l: 172.22.255.75 }
    openvpn:
      remote: 119.9.15.56
      rport: 58865
      port: 37169
      tun: 8
  - name: MWD
    as: 4242420002
    tunnels:
      - { r: 172.23.227.1, l: 172.22.255.72 }
      - { r: 'fd14:70d8:4a5a:1::1', l: 'fd14:70d8:4a5a:1::' }
    openvpn:
      remote: 103.24.132.66
      port: 37168
      rport: 57604
      tun: 7
  - name: gigadoc2
    as: 4242420003
    tunnels:
      - { r: 172.22.255.71 }
      - { r: 'fd14:70d8:4a5a:8::2' }
      # - { r: 'fe80::200:5efe:52d:6031%gre1' }
  - name: stv0g
    as: 76100
    tunnels:
      - { r: 172.22.255.37, l: 172.22.255.36 }
      - { r: 'fd14:70d8:4a5a::1', l: 'fd14:70d8:4a5a::' }
    openvpn:
      # XXX: add 'proto udp6' to config?
      remote: 2a03:b0c0:1:d0::2e3:c001
      port: 31218
      rport: 37163
      tun: 1
  - name: Nurtic-Vibe
    as: 4242420123
    tunnels:
      - { r: 172.23.162.208, l: 172.22.255.65 }
    openvpn:
      remote: de02.dn42.grmml.eu
      port: 37164
      rport: 2433
      tun: 3
  - name: petrus
    as: 64751
    tunnels:
      - { r: 172.22.151.230, l: 172.22.255.67 }
    openvpn:
      rport: 2323
      port: 37166
      remote: poum.tk
      tun: 5
  - name: nazco
    as: 76118
    tunnels:
      - { r: 172.23.138.1, l: 172.22.255.66 }
    openvpn:
      remote: dn42.peering.nazco.de
      port: 37165
      rport: 2626
      tun: 4
