---
- name: enable
  service: name=smtpd enabled=yes
  notify:
    - restart smtpd
- name: configure
  copy:
    src: "{{ item }}"
    dest: "/etc/mail/{{ item }}"
  with_items:
    - aliases
    - smtpd.conf
  notify:
    - restart smtpd
