# Missing:
# - OpenVPN
#   - automatically enumerate tun devices
#     - is that still required with dynamic tun?
# - IPSec
# - OSPF
# - Name server
# - Looking glass
# - DN42 specific mail server stuff?
#   - similar to PF config
---
- name: set up DN42 PF configuration
  template: src=roles/dn42/templates/pf.dn42.conf dest=/etc/pf.dn42.conf mode=0640
  notify:
    - reload pf ruleset

- name: install openvpn
  package: name=openvpn state=present
- name: create openvpn directories
  file: path=/etc/openvpn/dn42-{{ item.name }} state=directory
  with_items: "{{ peers|selectattr('openvpn', 'defined')|list }}"
- name: configure openvpn
  template: src=roles/dn42/templates/openvpn.conf dest=/etc/openvpn/dn42-{{ item.name }}/config
  with_items: "{{ peers|selectattr('openvpn', 'defined')|list }}"
  notify:
    - netstart
- name: load openvpn keys
  include_vars: "roles/dn42/vars/keys.yml"
  no_log: true
- name: deploy openvpn keys
  copy:
    dest: /etc/openvpn/dn42-{{ item.name }}/key
    content: "{{ openvpn_keys[item.name] }}"
  with_items: "{{ peers | selectattr('openvpn', 'defined')|list }}"
  notify:
    - netstart
- name: configure openvpn hostnames
  template: src=roles/dn42/templates/hostname dest=/etc/hostname.tun{{ item.openvpn.tun }}
  with_items: "{{ peers|selectattr('openvpn', 'defined')|list }}"
  notify:
    - netstart

- name: enable bgpd
  service: name=bgpd enabled=yes
  notify:
    - restart bgpd
- name: configure bgpd
  template: src=roles/dn42/templates/bgpd.conf dest=/etc/bgpd.conf mode=640
  notify:
    - reload bgp config

- name: create BGP peer directory
  file: path=/etc/bgp state=directory
- name: set up BGP peers
  template: src=roles/dn42/templates/bgp-peer.conf dest=/etc/bgp/{{ item.name }}.conf mode=640
  with_items: "{{ peers }}"
  notify:
    - reload bgp config
