# Missing:
# - OpenVPN
#   - automatically enumerate tun devices
#     - is that still required with dynamic tun?
# - IPSec
# - Looking glass
# - DN42 specific mail server stuff?
#   - similar to PF config
---
- name: set up DN42 PF configuration
  template:
    src: "{{ role_path }}/templates/pf.dn42.conf"
    dest: /etc/pf.dn42.conf
    mode: 0640
  notify:
    - reload pf ruleset

- include: vpn.yml
- include: bgp.yml
- include: dns.yml
